- name: Install wartest role
  hosts: all
  become: yes
  roles:
    - wartest

- name: Install pip3 and Docker module
  hosts: all
  become: yes
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install docker Python module
      pip:
        name: docker
        executable: pip3
